#!/bin/bash

CERT="-----BEGIN CERTIFICATE-----
MIICKTCCAdCgAwIBAgIBATAKBggqhkjOPQQDBDBGMUQwCQYDVQQGEwJVUzA3BgNV
BAMeMABrAG8AbgBuAGUAYwB0AC0AdABoAGEAaQAtAGEAaQByAHcAYQB5AHMALQBw
AG8AYzAeFw0yNTA0MDEwMjE1MzlaFw0zNTA0MDEwMjE1MzlaMEYxRDAJBgNVBAYT
AlVTMDcGA1UEAx4wAGsAbwBuAG4AZQBjAHQALQB0AGgAYQBpAC0AYQBpAHIAdwBh
AHkAcwAtAHAAbwBjMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEnmGQqQ3zUpC6
3pp/WINEErxl/+crv5WxsAjkgMvHbfQ4mXl0YfFfIeHeG73AzQR/Zd7Tvn6zKEO3
NCi8S0+jRKOBrjCBqzAMBgNVHRMBAf8EAjAAMAsGA1UdDwQEAwIABjAdBgNVHSUE
FjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwFwYJKwYBBAGCNxQCBAoMCGNlcnRUeXBl
MCMGCSsGAQQBgjcVAgQWBBQBAQEBAQEBAQEBAQEBAQEBAQEBATAcBgkrBgEEAYI3
FQcEDzANBgUpAQEBAQIBCgIBFDATBgkrBgEEAYI3FQEEBgIEABQACjAKBggqhkjO
PQQDBANHADBEAiBrZFqse/RZP5zWi/3wBYw35aI0+S9+u3F2TM31ADQocwIgWb/C
P6Cc/8UUtp2uCPFe6OCt5sObITszl7XYj2/pHwU=
-----END CERTIFICATE-----"

CERT_KEY="-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgMJWQCmcdS4KTl+0k
o7o+jz4R4sKWs04C3kFyzsLc9l6gCgYIKoZIzj0DAQehRANCAASeYZCpDfNSkLre
mn9Yg0QSvGX/5yu/lbGwCOSAy8dt9DiZeXRh8V8h4d4bvcDNBH9l3tO+frMoQ7c0
KLxLT6NE
-----END PRIVATE KEY-----"

docker run -d \
  -e "KONG_ROLE=data_plane" \
  -e "KONG_DATABASE=off" \
  -e "KONG_VITALS=off" \
  -e "KONG_CLUSTER_MTLS=pki" \
  -e "KONG_CLUSTER_CONTROL_PLANE=bf1a84ee7c.us.cp0.konghq.com:443" \
  -e "KONG_CLUSTER_SERVER_NAME=bf1a84ee7c.us.cp0.konghq.com" \
  -e "KONG_CLUSTER_TELEMETRY_ENDPOINT=bf1a84ee7c.us.tp0.konghq.com:443" \
  -e "KONG_CLUSTER_TELEMETRY_SERVER_NAME=bf1a84ee7c.us.tp0.konghq.com" \
  -e "KONG_CLUSTER_CERT=$CERT" \
  -e "KONG_CLUSTER_CERT_KEY=$CERT_KEY" \
  -e "KONG_LUA_SSL_TRUSTED_CERTIFICATE=system" \
  -e "KONG_KONNECT_MODE=on" \
  -e "KONG_UNTRUSTED_LUA=on" \
  -e "KONG_CLUSTER_DP_LABELS=created-by:quickstart,type:docker-linuxdockerOS" \
  -e "KONG_ROUTER_FLAVOR=expressions" \
  -e "KONG_CLUSTER_RPC=on" \
  -e KONG_ACTIVE_TRACING=on \
  -p 8000:8000 \
  -p 443:8443 \
  kong/kong-gateway:3.10
